### ISSUE TITLE
Plugin does not work

### ISSUE THREAD

**Issue by catfueledmayhem** [An00nymushun/DiscordEmojiParty#6]
When i trying to use this plugin, it does not work

**Comment by mrbsvf** [comment]
same

**Comment by An00nymushun** [comment]
How did you try to use it?

**Comment by TastesLikePanda** [comment]
> How did you try to use it?

when launching discord it just says that the addon could not be compiled.

TypeError: nodeHttps.Agent is not a constructor
    at eval (betterdiscord://plugins/EmojiParty.plugin.js:130:41)
    at eval (betterdiscord://plugins/EmojiParty.plugin.js:160:7)
    at eval (betterdiscord://plugins/EmojiParty.plugin.js:539:3)
    at Object.requireAddon (<anonymous>:4:43438)
    at Object.loadAddon (<anonymous>:4:9197)
    at Object.loadAddon (<anonymous>:4:41165)
    at Object.loadAllAddons (<anonymous>:4:11607)
    at Object.initialize (<anonymous>:4:6257)
    at Object.initialize (<anonymous>:4:40368)
    at Object.startup (<anonymous>:4:376262)
    
Same happens when trying to reinstal.

**Comment by mrbsvf** [comment]
> How did you try to use it?

Added it to BetterDiscord's plugin folder and enabled it. tried any number/type of emotes and didn't work

**Comment by MysticAx0lotl** [comment]
I have the same problem. It started right around the time that Discord pushed that update that broke Betterdiscord and most plugins for awhile

**Comment by StarNumber12046** [comment]
it should be fixed by someone, I'll try to open a PR

**Comment by P4ncake4451** [comment]
same issue

**Comment by AlphaBaqpla** [comment]
not fixed(

**Comment by nooksmr** [comment]
# This plugin is broken. 😪
Hoping for a patch/fix as soon as the developper could update it.
```fix
Better Discord 1.9.2
Stable 199933 (db1e138)
Host 1.0.9013 (32266)
```
```TypeScript
TypeError: nodeHttps.Agent is not a constructor
    at eval (betterdiscord://plugins/EmojiParty.plugin.js:130:41)
    at eval (betterdiscord://plugins/EmojiParty.plugin.js:160:7)
    at eval (betterdiscord://plugins/EmojiParty.plugin.js:539:3)
    at A.requireAddon (betterdiscord/renderer.js:4:35124)
    at A.loadAddon (betterdiscord/renderer.js:4:7625)
    at A.loadAddon (betterdiscord/renderer.js:4:32796)
    at A.reloadAddon (betterdiscord/renderer.js:4:8515)
    at AsyncFunction.<anonymous> (betterdiscord/renderer.js:4:5651)
   ```

**Comment by c0des1ay3r** [comment]
[My fork](https://github.com/c0des1ay3r/DiscordEmojiParty) works.

**Comment by Vitalya222** [comment]
> [My fork](https://github.com/c0des1ay3r/DiscordEmojiParty) works. Gonna make a PR on main tho.

how? i cant

**Comment by lunatunawuna** [comment]
![image](https://github.com/An00nymushun/DiscordEmojiParty/assets/141763131/ecac44f5-025f-443b-9051-ffc8d4f23ba2)

**Comment by ndcrd** [comment]
Repo is abandoned, I've made a workaround to send image as an attachment. Will do autosend message once I get some free time. Enjoy the [fork ](https://github.com/nikolai-imversed/DiscordEmojiParty)

**Comment by ccjmne** [comment]
Hey @nikolai-imversed,

I just downloaded your fork and set it up. No more errors on start-up, hooray!

However, it doesn't seem to do... anything?
I thought all I had to do was send a message with at least five emojis. Am I missing something? Is there anything I can do to help?

**Comment by ndcrd** [comment]
> Hey @nikolai-imversed,
> 
> I just downloaded your fork and set it up. No more errors on start-up, hooray!
> 
> However, it doesn't seem to do... anything? I thought all I had to do was send a message with at least five emojis. Am I missing something? Is there anything I can do to help?

Hi, It shall form emojis into an attachment, but maybe new updates broke this plugin again.
